FROM python:3.10-slim

WORKDIR /app

COPY infra/requirements.ui.txt .
RUN pip install --no-cache-dir -r requirements.ui.txt

COPY src/ui/ .

EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
